# .readthedocs.yml

version: 2

build:
  os: ubuntu-18.04
  image: latest
  
sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
    
conda:
  environment: docs/requirements.yaml
