# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  
sphinx:
  configuration: docs/conf.py

python:
  use_system_site_packages: true
  install:
    - requirements: docs/requirements.yaml
    - method: pip
      path: .
      extra_requirements:
        - docs


conda:
  environment: docs/requirements.yaml
