# .readthedocs.yml

version: 2

build:
  image: latest
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml
